//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]

namespace myMember.Models
{
    #region 內容
    
    /// <summary>
    /// 沒有可用的中繼資料文件。
    /// </summary>
    public partial class myMemberEntities : ObjectContext
    {
        #region 建構函式
    
        /// <summary>
        /// 使用在應用程式組態檔的 'myMemberEntities' 區段中找到的連接字串，初始化新的 myMemberEntities 物件。
        /// </summary>
        public myMemberEntities() : base("name=myMemberEntities", "myMemberEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// 初始化新的 myMemberEntities 物件。
        /// </summary>
        public myMemberEntities(string connectionString) : base(connectionString, "myMemberEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// 初始化新的 myMemberEntities 物件。
        /// </summary>
        public myMemberEntities(EntityConnection connection) : base(connection, "myMemberEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region 部分方法
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet 屬性
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        public ObjectSet<member> member
        {
            get
            {
                if ((_member == null))
                {
                    _member = base.CreateObjectSet<member>("member");
                }
                return _member;
            }
        }
        private ObjectSet<member> _member;

        #endregion
        #region AddTo 方法
    
        /// <summary>
        /// 將新物件加入 member EntitySet 的方法已被取代。請考慮改為使用關聯的 ObjectSet&lt;T&gt; 屬性的 .Add 方法。
        /// </summary>
        public void AddTomember(member member)
        {
            base.AddObject("member", member);
        }

        #endregion
    }
    

    #endregion
    
    #region 實體
    
    /// <summary>
    /// 沒有可用的中繼資料文件。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="myMemberModel", Name="member")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class member : EntityObject
    {
        #region Factory 方法
    
        /// <summary>
        /// 建立新 member 物件。
        /// </summary>
        /// <param name="id">id 屬性的初始值。</param>
        /// <param name="username">username 屬性的初始值。</param>
        /// <param name="password">password 屬性的初始值。</param>
        /// <param name="name">name 屬性的初始值。</param>
        /// <param name="sex">sex 屬性的初始值。</param>
        /// <param name="mail">mail 屬性的初始值。</param>
        /// <param name="isadmin">isadmin 屬性的初始值。</param>
        public static member Createmember(global::System.Int32 id, global::System.String username, global::System.String password, global::System.String name, global::System.String sex, global::System.String mail, global::System.Boolean isadmin)
        {
            member member = new member();
            member.id = id;
            member.username = username;
            member.password = password;
            member.name = name;
            member.sex = sex;
            member.mail = mail;
            member.isadmin = isadmin;
            return member;
        }

        #endregion
        #region 基本屬性
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String username
        {
            get
            {
                return _username;
            }
            set
            {
                OnusernameChanging(value);
                ReportPropertyChanging("username");
                _username = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("username");
                OnusernameChanged();
            }
        }
        private global::System.String _username;
        partial void OnusernameChanging(global::System.String value);
        partial void OnusernameChanged();
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String password
        {
            get
            {
                return _password;
            }
            set
            {
                OnpasswordChanging(value);
                ReportPropertyChanging("password");
                _password = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("password");
                OnpasswordChanged();
            }
        }
        private global::System.String _password;
        partial void OnpasswordChanging(global::System.String value);
        partial void OnpasswordChanged();
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String sex
        {
            get
            {
                return _sex;
            }
            set
            {
                OnsexChanging(value);
                ReportPropertyChanging("sex");
                _sex = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("sex");
                OnsexChanged();
            }
        }
        private global::System.String _sex;
        partial void OnsexChanging(global::System.String value);
        partial void OnsexChanged();
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String mail
        {
            get
            {
                return _mail;
            }
            set
            {
                OnmailChanging(value);
                ReportPropertyChanging("mail");
                _mail = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("mail");
                OnmailChanged();
            }
        }
        private global::System.String _mail;
        partial void OnmailChanging(global::System.String value);
        partial void OnmailChanged();
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String authcode
        {
            get
            {
                return _authcode;
            }
            set
            {
                OnauthcodeChanging(value);
                ReportPropertyChanging("authcode");
                _authcode = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("authcode");
                OnauthcodeChanged();
            }
        }
        private global::System.String _authcode;
        partial void OnauthcodeChanging(global::System.String value);
        partial void OnauthcodeChanged();
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean isadmin
        {
            get
            {
                return _isadmin;
            }
            set
            {
                OnisadminChanging(value);
                ReportPropertyChanging("isadmin");
                _isadmin = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("isadmin");
                OnisadminChanged();
            }
        }
        private global::System.Boolean _isadmin;
        partial void OnisadminChanging(global::System.Boolean value);
        partial void OnisadminChanged();

        #endregion
    
    }

    #endregion
    
}
